use_frameworks!

platform :ios, '10.0'

target 'EthereumSDK_Example' do
  pod 'EthereumSDK', :path => '../'
  pod 'web3swift'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  
  target 'EthereumSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
